# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'coffee_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for coffee_app

end

target 'coffee_app-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for coffee_app-tvOS

  target 'coffee_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
